### ISSUE TITLE
TC 10: Permissions

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input-manual-tests#22]
** Requirements **
- Input app is FRESHLY installed or alternatively, you have wiped the cache and storage

---

### Test A - Storage permission

**Test Steps**

**A1.** Run fresh installed application and do not grant Storage permission.

**A2.** The app should run and prompts users on the home screen to grant Storage permission from settings

**A3.** Select the option from A2. and grant Storage permission.

**A4.** Restart the app and it should show you the default projects

---

### Test B - Location permission

**Test Steps**

**B1.** Run fresh installed application and do not grant Location permission.

**B2.** The app should run and should take you to the home screen

**B3.** Select a project to open

**B4.** Press the GPS icon

**B5.** It should show a popup telling user to enable location

---

### Test C - Camera permission

**Test Steps**

**C1.** Run fresh installed application and the app should not ask for camera permission

**C2.** Open a project with photos in forms (e.g. lutraconsulting\test_forms)

**C3.** Add a feature and when the form appears, select to add a photo from camera

**C4.** The camera permission should appear

**C5.** Denying it: should show a toast that you need camera permission

**C6.** Accepting it: should allow you taking a photo using camera

**Comment by PeterPetrik** [comment]
@saberraz can we  merge this one with https://github.com/lutraconsulting/input-manual-tests/issues/18 ?
